server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Serve JS/CSS assets properly
    location /assets/ {
        try_files $uri =404;
    }

    # SPA fallback (React Router)
    location / {
        try_files $uri /index.html;
    }
}
